# Generated by Django 3.0.6 on 2020-05-21 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='population_in',
            field=models.CharField(default='thousands', max_length=30),
        ),
        migrations.AddField(
            model_name='country',
            name='population_in',
            field=models.CharField(default='thousands', max_length=30),
        ),
        migrations.AddField(
            model_name='religion',
            name='population_in',
            field=models.CharField(default='thousands', max_length=30),
        ),
        migrations.AlterField(
            model_name='city',
            name='population',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='country',
            name='population',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='religion',
            name='population',
            field=models.FloatField(),
        ),
    ]
