# Generated by Django 3.0.6 on 2020-05-25 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('strain', models.CharField(max_length=100)),
                ('average_mortality_rate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Pandemic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('disease', models.CharField(max_length=75)),
                ('total_deaths', models.IntegerField()),
                ('year_from', models.IntegerField()),
                ('year_to', models.IntegerField()),
                ('embed_html', models.CharField(max_length=3000)),
            ],
        ),
    ]
