# Generated by Django 3.0.6 on 2020-05-25 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pandemics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disease',
            old_name='strain',
            new_name='type',
        ),
    ]
